export const motivationalQuotes = [
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Believe you can and you're halfway there.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Your time is limited, so don’t waste it living someone else’s life.",
  "Happiness depends upon ourselves.",
  "Do what you can, with what you have, where you are.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "Don’t count the days, make the days count.",
  "The best way to predict the future is to invent it.",
  "I never dreamed about success, I worked for it.",
  "Dream big and dare to fail.",
  "In the middle of every difficulty lies opportunity.",
  "If you are not willing to risk the unusual, you will have to settle for the ordinary.",
  "Act as if what you do makes a difference. It does.",
  "Do not wait to strike till the iron is hot, but make it hot by striking.",
  "Opportunities don't happen, you create them.",
  "Don’t let yesterday take up too much of today.",
  "Fall seven times and stand up eight.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Limit your ‘always’ and your ‘nevers’.",
  "Turn your wounds into wisdom.",
  "If you can dream it, you can do it.",
  "Start where you are. Use what you have. Do what you can.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Everything has beauty, but not everyone sees it.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Courage is grace under pressure.",
  "The secret of getting ahead is getting started.",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
  "It always seems impossible until it’s done.",
  "Don’t quit. Suffer now and live the rest of your life as a champion.",
  "Quality is not an act, it is a habit.",
  "A journey of a thousand miles begins with a single step.",
  "You miss 100% of the shots you don’t take.",
  "Don’t be afraid to give up the good to go for the great.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Go the extra mile. It’s never crowded there.",
  "I can and I will. Watch me.",
  "Act without expectation.",
  "The man who moves a mountain begins by carrying away small stones.",
  "Doubt kills more dreams than failure ever will.",
  "The way to get started is to quit talking and begin doing.",
  "Perseverance is failing 19 times and succeeding the 20th.",
  "Don’t wish it were easier. Wish you were better.",
  "Be yourself; everyone else is already taken.",
  "Push yourself, because no one else is going to do it for you.",
  "Discipline is the bridge between goals and accomplishment.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream it. Wish it. Do it.",
  "Great things never come from comfort zones.",
  "The key to success is to focus on goals, not obstacles.",
  "Small progress is still progress.",
  "The expert in anything was once a beginner.",
  "Don't stop when you’re tired. Stop when you’re done.",
  "Work hard in silence, let your success be your noise.",
  "Difficult roads often lead to beautiful destinations.",
  "Stay positive, work hard, make it happen.",
  "Don’t wait for opportunity. Create it.",
  "Be so good they can’t ignore you.",
  "The best revenge is massive success.",
  "Do one thing every day that scares you.",
  "If you want to lift yourself up, lift up someone else.",
  "Work like you don’t need the money. Love like you’ve never been hurt. Dance like nobody’s watching.",
  "You must be the change you wish to see in the world.",
  "Don’t let the fear of losing be greater than the excitement of winning.",
  "Try to be a rainbow in someone’s cloud.",
  "Hustle beats talent when talent doesn’t hustle.",
  "We generate fears while we sit. We overcome them by action.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Don’t compare yourself with anyone else. Compare yourself with the person you were yesterday.",
  "Winners are not afraid of losing. But losers are.",
  "Do not wait: the time will never be ‘just right’.",
  "If opportunity doesn’t knock, build a door.",
  "A winner is a dreamer who never gives up.",
  "Action is the foundational key to all success.",
  "Knowledge without action is meaningless.",
  "Whether you think you can or you think you can’t, you’re right.",
  "A person who never made a mistake never tried anything new.",
  "The best preparation for tomorrow is doing your best today.",
  "Failure will never overtake me if my determination to succeed is strong enough.",
  "Big jobs usually go to the men who prove their ability to outgrow small ones.",
  "You can waste your lives drawing lines. Or you can live your life crossing them.",
  "Success is not in what you have, but who you are.",
  "Energy and persistence conquer all things.",
  "Our greatest glory is not in never falling, but in rising every time we fall.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",
  "You are never too old to set another goal or to dream a new dream.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Start today, not tomorrow. If you start tomorrow, you’ll keep saying it.",
  "The best way out is always through.",
  "Everything you can imagine is real.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "You don’t find willpower, you create it."
];

